/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.23.2
// source: recipe.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./recipe_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.RecipeServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.RecipeServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetRecipeRequest,
 *   !proto.RecipeResponse>}
 */
const methodDescriptor_RecipeService_GetRecipe = new grpc.web.MethodDescriptor(
  '/RecipeService/GetRecipe',
  grpc.web.MethodType.UNARY,
  proto.GetRecipeRequest,
  proto.RecipeResponse,
  /**
   * @param {!proto.GetRecipeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.RecipeResponse.deserializeBinary
);


/**
 * @param {!proto.GetRecipeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.RecipeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.RecipeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.RecipeServiceClient.prototype.getRecipe =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/RecipeService/GetRecipe',
      request,
      metadata || {},
      methodDescriptor_RecipeService_GetRecipe,
      callback);
};


/**
 * @param {!proto.GetRecipeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.RecipeResponse>}
 *     Promise that resolves to the response
 */
proto.RecipeServicePromiseClient.prototype.getRecipe =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/RecipeService/GetRecipe',
      request,
      metadata || {},
      methodDescriptor_RecipeService_GetRecipe);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SearchRecipesRequest,
 *   !proto.SearchRecipesResponse>}
 */
const methodDescriptor_RecipeService_SearchRecipes = new grpc.web.MethodDescriptor(
  '/RecipeService/SearchRecipes',
  grpc.web.MethodType.UNARY,
  proto.SearchRecipesRequest,
  proto.SearchRecipesResponse,
  /**
   * @param {!proto.SearchRecipesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.SearchRecipesResponse.deserializeBinary
);


/**
 * @param {!proto.SearchRecipesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SearchRecipesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SearchRecipesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.RecipeServiceClient.prototype.searchRecipes =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/RecipeService/SearchRecipes',
      request,
      metadata || {},
      methodDescriptor_RecipeService_SearchRecipes,
      callback);
};


/**
 * @param {!proto.SearchRecipesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SearchRecipesResponse>}
 *     Promise that resolves to the response
 */
proto.RecipeServicePromiseClient.prototype.searchRecipes =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/RecipeService/SearchRecipes',
      request,
      metadata || {},
      methodDescriptor_RecipeService_SearchRecipes);
};


module.exports = proto;

